### ISSUE TITLE
ReceivedEmailCount not giving correct value

### ISSUE THREAD

**Issue by karlgjertsen** [EdenRidgway/nDumbster#1]
I moved from the original nDumbster to this version due to slow test times. Whilst the performance of this version is much better, I get the wrong value returned from ReceivedEmailCount().

Is this a known issue?

**Comment by EdenRidgway** [comment]
My apologies, I fixed this some time ago but because I didn't think anyone was using this I hadn't uploaded my change. The latest version should fix your problem, but be aware that I also changed MailMessage to the standard System.Net.Mail.Message class and not the OpenPop Message type. 

I have to admit I haven't really looked at this for quite a while so there may be some other gremlins lurking around. I hope that helps.

**Comment by karlgjertsen** [comment]
I'm downloading the newest version now. Thank you.
It sounds as though you think nobody is using this...Why do you think that? I think this is a great way to test email functionality.

**Comment by karlgjertsen** [comment]
I am still getting an issue. If I run the tests individually, they all work. If I run them all together, then I get an error in the tests that use the smtpService. The count is returning 0 when it is sending an email.
I will look into this in more detail and let you know if I can find where the issue is.

**Comment by paul-connor** [comment]
I started using this version of nDumbster too.  I'm also running into the similar problem, if I run all the tests then SendMessageWithAttachment fails to receive a message.  Run individually, then it passes.

**Comment by paul-connor** [comment]
I'm looking into it further.  When I re-ordered the test cases, then a different test (specifically the third test in the file, which was SendTwoMessages) failed while all the others passed.

**Comment by EdenRidgway** [comment]
Hi Paul. Thanks for logging this issue. I've changed the way it is stopped and this seems to have resolved the issue (at least for me). Would you mind getting the latest version and trying again?

I wish I had the time to rewrite the code as there is a lot of room for improvement. One could structure it such that tests could be better isolated (say with a disposable server instantiated in a using block with a random port). Well for the time being it would be good to get this core piece sorted. Thanks.

**Comment by paul-connor** [comment]
It's working for me now.  Thanks!

**Comment by karlgjertsen** [comment]
Sorry, I'm still getting an error when I try to run multiple tests. If I run a test on it's own, it passes, but as part of a larger group of tests, I get failures.

**Comment by EdenRidgway** [comment]
When the tests are being run is the server being stopped and started for each run or are you reusing the same one?

**Comment by karlgjertsen** [comment]
I'm reusing the same one, but calling the ClearReceivedEmail() method.
Should I be using different server instances?

**Comment by jezzsantos** [comment]
@kgjertsen  Did this ever get resolved? I just opened another issue before I saw this thread. Sounds related?
What did you do to work around it?

**Comment by karlgjertsen** [comment]
Hi Jezz,

This was never fixed, so I wrote my own solution!

It'll go into Beta over the next few weeks and I can update you when it's ready.

Regards,

Karl

**Comment by jezzsantos** [comment]
Thanks Karl, I will definitely look for it. Please keep me in the loop.
I have had to disable my failing test in the meantime.

However, I think I may have a clue as to why this doesn't work in the multi-test scenario.
Over on the other thread: https://github.com/EdenRidgway/nDumbster/issues/2, perhaps a timeout issue?

**Comment by EdenRidgway** [comment]
Hi Jezz, I recall looking at this sometime ago and thinking that the way the NDumbster code is structured needed work. Would it be possible to add a quick test project example that I could use to see if it can be resolved without starting from scratch? Of course it is great that kgjertsen has another solution in the works too as the nDumbster code base probably needs major work (I suspect it was most likely a factor of how it was ported / based on the Java version).

I'll try to spend some time tonight or on the weekend to take a look and see what is going on.

**Comment by jezzsantos** [comment]
Hey Eden, thanks heaps for responding. This is really important work. 

I came across your code while looking for a version of nDumbster I could string name sign. I am sure I am not the only one who needs that. Your project looked the most promising.

Its real important stuff for those serious about automated testing of solutions with email.

I am not sure I can create the solution you are looking from from my code, its a private repo.
However, I have a hunch that if you were to try testing several tests with significant delays Thread.Sleep() delays between them to total about 5-10mins of total testing time, you would see what we are seeing, i.e. failing tests towards the 3-5min mark. At least that is my current hypothesis. 

I'd love to engage and help you, because as I say, we are dead int eh water right now unable to use the current codebase at all.

**Comment by EdenRidgway** [comment]
Hi Jezz, I've added a test project called nDumbster.MsTests trying to replicate the problem. If you have a chance I'd really appreciate it if you could take a look at it and see if it:
1) Is an accurate reflection of the way you are looking to use and test with NDumbster
2) If you get the same issue as you are experiencing when running your tests

Unfortunately at the moment I'm not getting the issue, so any help in recreating it would be really great. Is there any possibility of multiple simultaneous tests being run?

**Comment by jezzsantos** [comment]
Hi Eden,

Yes, I had a big go at this today as well. This is what I tried to isolate the problem. Gain, I an getting consistent failures when my SmtpServer tests are part of a larger test run, and not failing when those tests are run either individually or as a group on their own.

My hunch was that there may be some kind of timeout that is making the smtpserver fail to receive email sometime after calling Start() and before accessing the ReceivedEmail property. In between for every test in my large runs I am calling ClearReceivedEmail() for each test regardless even though 90% of the tests don't use the Smtp Server. MY large test runs complete i just less than 5mins toatl.

OK, here is what I tried to repro the problem: 
1. I created a simple test that sends an email and tests whether it arrives by checkig the ReceivedEmail property. When it is run is passes consistently
2. Then I decided to duplicate the same test code again (in same test) twice in two identical blocks one after the other, with a ClearReceivedEmail call between. It passes consistently
3. Then I added a 5min delay between the two blocks. It passes consistently
4. Then I added a while for loop sleeping for 30secs and then calling ClearReceivedMail every 30secs, for a total of 5mins, between the two test codes blocks. It passed consistently.
5. I ran out of ideas on this hypothesis.

Net result I cant repro the problem like this. Just introducing a delay between Start() and ClearReceivedEmail and checking the ReceivedEmail calls does not make it fail. There is something else going on here that makes my tests fail consistently when they are run in a larger test run with other tests that do not use the Smtp server, but at the start of each test we are calling ClearRecievedEmail.
I guess this might be useful data to help identify where the problem isn't but I have to say I am left even more baffled now.

Would you have any clues?

**Comment by karlgjertsen** [comment]
For me it happened when I was running multiple tests. On its own, the test would pass, when ran with other tests it would fail.

Regards,

Karl

On 26 Apr 2014, at 13:20, "Jezz Santos" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Eden,

Yes, I had a big go at this today as well. This is what I tried to isolate the problem. Gain, I an getting consistent failures when my SmtpServer tests are part of a larger test run, and not failing when those tests are run either individually or as a group on their own.

My hunch was that there may be some kind of timeout that is making the smtpserver fail to receive email sometime after calling Start() and before accessing the ReceivedEmail property. In between for every test in my large runs I am calling ClearReceivedEmail() for each test regardless even though 90% of the tests don't use the Smtp Server. MY large test runs complete i just less than 5mins toatl.

OK, here is what I tried to repro the problem:
1. I created a simple test that sends an email and tests whether it arrives by checkig the ReceivedEmail property. When it is run is passes consistently
2. Then I decided to duplicate the same test code again (in same test) twice in two identical blocks one after the other, with a ClearReceivedEmail call between. It passes consistently
3. Then I added a 5min delay between the two blocks. It passes consistently
4. Then I added a while for loop sleeping for 30secs and then calling ClearReceivedMail every 30secs, for a total of 5mins, between the two test codes blocks. It passed consistently.
5. I ran out of ideas on this hypothesis.

Net result I cant repro the problem like this. Just introducing a delay between Start() and ClearReceivedEmail and checking the ReceivedEmail calls does not make it fail. There is something else going on here that makes my tests fail consistently when they are run in a larger test run with other tests that do not use the Smtp server, but at the start of each test we are calling ClearRecievedEmail.
I guess this might be useful data to help identify where the problem isn't but I have to say I am left even more baffled now.

Would you have any clues?

**Comment by EdenRidgway** [comment]
Hi Jezz

Thanks a lot for trying to replicate the problem. I've also struggled to get it to fail in both a long running and multiple calls test scenario. There has to be some strange threading issue or race condition somewhere so I've done is tweaked the code that clears and returns the list of emails to see if that helps. 

The ClearReceivedEmail method now does a (it used to create a new queue) 

``` C#
while (_receivedMail.TryDequeue(out mailMessage)) {} 
```

and the ReceivedEmail property takes a snapshot of the queue:

``` C#
return _receivedMail.ToList();
```

I'm not super confident that it will resolve the issue but hopefully it eliminates another possibility and we can isolate the problem.

**Comment by EdenRidgway** [comment]
Hi Jezz, did the changes above make any difference when running your battery of tests?

**Comment by jezzsantos** [comment]
Hi Eden, no they did not. I had a thought last night to try another experiment first before reporting back. Sorry day job getting in the way, will be fully engaged shortly

**Comment by jezzsantos** [comment]
Hi Eden,

Sorry its been a while.
I have some good news for you.
In my case, all my tests are now working with this new version.
I am going to be quite honest with you. I found a problem with my code that was sending the messages to the SMTP server, and once I had that fixed, your latest version is working with it.
So, the problem is that I cannot confirm that your latest fix, actually fixed my problems or not. All I can tell you is that it is working now.

If you take no further action, I will understand. So I wanted to take this opportunity to thank you for responding and taking action.

I will say again. This is a tremendously useful an important tool for those of us who do a lot of automated testing, that I am sure many others are using successfully. 
Thanks so much for you time on this.

regards,

**Comment by EdenRidgway** [comment]
Hi Jezz, thank you very much for getting back to me. I appreciate the feedback and I'm really glad that it is working for you.
